include("clipping-test.jl")
# include("copy_path.jl") # still gives
# julia(92954,0x7fff7d0e6000) malloc: *** error for object 0x7fde1c3b1800: pointer being freed was not allocated
include("heart-julia.jl")
include("images-with-alpha.jl")
include("julia-logo-draw-eps.jl")
include("julia-logo-draw.jl")
include("luxor-test1.jl")
include("matrix-tests.jl")
include("palette_test.jl")
include("point-inside-polygon.jl")
include("point-intersection.jl")
include("polygon-centroid-sort-test.jl")
include("polysplit.jl")
include("pretty-poly-test.jl")
include("polygon-test.jl")
include("randomsinecurves.jl")
include("sector-test.jl")
include("sierpinski-svg.jl")
include("sierpinski.jl")
include("simplify-polygons.jl")
include("star-test.jl")
include("test-holes.jl")
include("test-image.jl")
include("text-path-clipping.jl")
include("tiling-images.jl")
include("turtle.jl")
