name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    tags: '*'
jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ['1.9', '1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        arch: [x64]
        allow_failure: [false]
        include:
          - version: 'nightly'
            os: ubuntu-latest
            arch: x64
            allow_failure: true
          - version: 'nightly'
            os: macOS-latest
            arch: x64
            allow_failure: true
          - version: 'nightly'
            os: windows-latest
            arch: x64
            allow_failure: true
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - uses: actions/cache@v3
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - name: Update fonts
        run: |
          sudo cp ~/.julia/packages/MathTeXEngine/*/assets/fonts/ComputerModern/*.ttf /usr/local/share/fonts/ &&
          sudo cp ~/.julia/packages/MathTeXEngine/*/assets/fonts/NewComputerModern/NewCM* /usr/local/share/fonts/ &&
          fc-cache -rv &&
          fc-list -v | grep postscriptname
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using Luxor
            doctest(Luxor)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
